[linters]
disable-all=true
enable = [
    "errcheck",
    "gosimple",
    "govet",
    "ineffassign",
    "staticcheck",
    "typecheck",
    "unused",
    "forbidigo",
    "goimports",
    "gosec",
    "importas",
    "nilnil",
    "unconvert",
]